server:
  servlet:
    context-path: /
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.art.manager.mapper


spring:
  #mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/saas_hhys?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
    username: art
    password: ENC(zatm0z7yg1TvhjiU/rGEiw==)
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
    #redis
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    jedis:
      pool:
        max-idle: 5
        min-idle: 0
        max-active: 20

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params=count: countSql
  returnPageInfo: check

#logger
logging:
  config: classpath:logback-manager.xml

web:
  host: http://hhshy.grandcnart.com/wechat/index.html#
  redirectUrl: http://hhshy.grandcnart.com/wechat/jump.html?target=http://hhshy.grandcnart.com/wechat/index.html_/login?
  indexUrl: http://hhshy.grandcnart.com/wechat/jump.html?target=http://hhshy.grandcnart.com/wechat/index.html_/

upload:
  picture:
    url:
